/*
 * Copyright (c) 2026 Ivan Zhukov. All Rights Reserved.
 * Email: ivzhuk7@gmail.com
 */

#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "MetaRoadBakeSettings.generated.h"

/** Where auto-generated road-mesh assets are stored (mirrors EModelingModeAssetGenerationLocation). */
UENUM()
enum class EMetaRoadAssetGenerationLocation : uint8
{
	/** In a path relative to the current Level/World file (the level's content folder). */
	WorldRelative,
	/** In the top-level /Game content folder. */
	Global,
	/** In the folder currently selected in the Content Browser, if one is available (else falls back). */
	CurrentAssetBrowserPath
};

/** How generated assets are saved (mirrors EModelingModeAssetGenerationBehavior). */
UENUM()
enum class EMetaRoadAssetGenerationBehavior : uint8
{
	/** Create the asset and immediately save it to disk. */
	AutoGenerateAndAutosave,
	/** Create the asset and mark it dirty, but do not auto-save (the user saves manually). */
	AutoGenerateButDoNotAutosave,
	/** Prompt for a folder/name via a save dialog for each generated asset. */
	InteractivePromptToSave
};

/** How a re-bake / Clear disposes of the mesh assets produced by the previous bake. */
UENUM()
enum class EMetaRoadCleanStrategy : uint8
{
	/** Move the previous bake's generated mesh assets into a _Trash subfolder instead of deleting.
	 *  Reversible: the re-bake stays fully undoable (Ctrl+Z restores the old actor with valid mesh
	 *  references) and nothing is lost from disk. */
	MoveToTrash,

	/** Permanently delete the previous bake's generated mesh assets from disk. Ctrl+Z still restores
	 *  the old actor, but its mesh references become empty; pre-bake undo history is cleared by
	 *  ForceDeleteObjects. */
	PermanentDelete,
};

/**
 * UMetaRoadBakeSettings
 *
 * Settings for the Bake action (shown in the "Bake" palette panel via an IDetailsView). A single
 * config-backed instance (the CDO, see Get()) edited in the panel and read by the bake pipeline to decide
 * where generated road-mesh assets are written. Mirrors the "Generated Assets" category of UE's
 * UModelingToolsEditorModeSettings — the path resolver (AssetUtils::GetNewAssetPathName) reads these.
 */
UCLASS(config = EditorPerProjectUserSettings)
class METAROADEDITOR_API UMetaRoadBakeSettings : public UObject
{
	GENERATED_BODY()

public:
	UMetaRoadBakeSettings();

	/** Where auto-generated assets are stored. */
	UPROPERTY(EditAnywhere, config, Category = "Generated Assets")
	EMetaRoadAssetGenerationLocation GenerationLocation = EMetaRoadAssetGenerationLocation::WorldRelative;

	/** How generated assets are saved on creation. */
	UPROPERTY(EditAnywhere, config, Category = "Generated Assets")
	EMetaRoadAssetGenerationBehavior GenerationMode = EMetaRoadAssetGenerationBehavior::AutoGenerateButDoNotAutosave;

	/** Path (relative to the resolved root) that auto-generated assets are placed in.
	 *  Ignored when GenerationLocation is CurrentAssetBrowserPath. */
	UPROPERTY(EditAnywhere, config, Category = "Generated Assets",
		meta = (EditCondition = "GenerationLocation != EMetaRoadAssetGenerationLocation::CurrentAssetBrowserPath", EditConditionHides))
	FString AutoGeneratedAssetPath = TEXT("_GENERATED");

	/** If true, assets generated for an unsaved level are stored in the top-level /Game folder instead of /Temp.
	 *  Only relevant for WorldRelative (only it can resolve to /Temp). */
	UPROPERTY(EditAnywhere, config, Category = "Generated Assets",
		meta = (EditCondition = "GenerationLocation == EMetaRoadAssetGenerationLocation::WorldRelative", EditConditionHides))
	bool bStoreUnsavedLevelAssetsInTopLevelGameFolder = true;

	/** If true, generated assets are placed in a per-user subfolder under the auto-generated path.
	 *  Ignored when GenerationLocation is CurrentAssetBrowserPath. */
	UPROPERTY(EditAnywhere, config, Category = "Generated Assets",
		meta = (EditCondition = "GenerationLocation != EMetaRoadAssetGenerationLocation::CurrentAssetBrowserPath", EditConditionHides))
	bool bUsePerUserAutogenSubfolder = true;

	/** Optional override for the per-user subfolder name (defaults to the OS user name). */
	UPROPERTY(EditAnywhere, config, Category = "Generated Assets",
		meta = (EditCondition = "bUsePerUserAutogenSubfolder && GenerationLocation != EMetaRoadAssetGenerationLocation::CurrentAssetBrowserPath", EditConditionHides))
	FString AutogenSubfolderUserNameOverride;

	/** If true, a short random hex string is appended to each generated asset's name to keep it unique. */
	UPROPERTY(EditAnywhere, config, Category = "Generated Assets")
	bool bAppendRandomStringToName = true;

	/** How a re-bake / Clear disposes of the mesh assets the previous bake generated. See EMetaRoadCleanStrategy. */
	UPROPERTY(EditAnywhere, config, Category = "Generated Assets")
	EMetaRoadCleanStrategy CleanStrategy = EMetaRoadCleanStrategy::PermanentDelete;

	/** The single shared instance (CDO), persisted to the editor config. */
	static UMetaRoadBakeSettings* Get() { return GetMutableDefault<UMetaRoadBakeSettings>(); }

#if WITH_EDITOR
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
#endif
};
